name: markdown-lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown links/style
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md
